# Generated by Django 5.0 on 2023-12-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp5', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(default=79999999999),
        ),
    ]
